#!/usr/bin/env python3
"""
scripts/generate_ward_docs.py
─────────────────────────────
Reads ward_config.yml and writes two ward-specific RAG docs into
backend/data/rag_docs/:
  - ward_directory.md      (replaces ahu_directory.md for this deployment)
  - ward_system_guide.md   (replaces wach_system_guide.md for this deployment)

Usage (from project root):
    python -m scripts.generate_ward_docs
    python scripts/generate_ward_docs.py

Idempotent — overwrites existing files on each run.
Falls back to ward_config.example.yml if ward_config.yml is not found.
Exits 0 with a warning if neither config file exists.
"""
from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RAG_DOCS_DIR = PROJECT_ROOT / "backend" / "data" / "rag_docs"


# ── Config loading ────────────────────────────────────────────────────────────

def load_config(config_path: Path | None = None) -> dict | None:
    """Load ward config YAML. Returns None if no config file exists."""
    try:
        import yaml
    except ImportError:
        print("[ward_docs] ERROR: PyYAML not installed. Run: pip install pyyaml", file=sys.stderr)
        sys.exit(1)

    candidates = [config_path] if config_path else [
        PROJECT_ROOT / "ward_config.yml",
        PROJECT_ROOT / "ward_config.example.yml",
    ]

    for path in candidates:
        if path and path.exists() and path.stat().st_size > 0:
            with open(path) as f:
                return yaml.safe_load(f)

    return None


# ── Device resolution ─────────────────────────────────────────────────────────

def resolve_devices(level: dict, device_prefix: str) -> list[str]:
    """Return the list of device IDs for a level entry.

    Supports two formats:
      devices: [e0301, e0302, ...]   → returns the list as-is
      ahus: N                        → generates prefix + level:02d + nn:02d
    """
    if "devices" in level:
        return list(level["devices"])
    if "ahus" in level:
        lvl = level["level"]
        return [f"{device_prefix}{lvl:02d}{n:02d}" for n in range(1, level["ahus"] + 1)]
    raise ValueError(
        f"Level {level.get('level')} must have either 'devices' list or 'ahus' count."
    )


# ── Markdown generators ───────────────────────────────────────────────────────

def generate_ward_directory(config: dict) -> str:
    """Generate ward_directory.md content from config dict."""
    prefix = config.get("device_prefix", "e")
    hospital = config["hospital"]
    ward = config["ward"]
    levels = config["levels"]

    all_devices = []
    level_sections: list[str] = []

    for lvl in levels:
        devices = resolve_devices(lvl, prefix)
        all_devices.extend(devices)
        device_list = ", ".join(devices)
        level_sections.append(
            f"### {lvl['name']}\n"
            f"**Devices ({len(devices)} AHUs):** {device_list}\n"
        )

    total = len(all_devices)
    first_id = all_devices[0] if all_devices else "—"
    last_id = all_devices[-1] if all_devices else "—"
    num_levels = len(levels)

    header = (
        f"# AHU Directory — {ward}, {hospital}\n\n"
        f"**Total:** {total} AHUs across {num_levels} levels "
        f"(device IDs {first_id}–{last_id})\n\n"
        f"<!-- generated by scripts/generate_ward_docs.py -->\n\n"
    )

    return header + "\n".join(level_sections)


def generate_ward_system_guide(config: dict) -> str:
    """Generate ward_system_guide.md content from config dict."""
    prefix = config.get("device_prefix", "e")
    hospital = config["hospital"]
    ward = config["ward"]
    levels = config["levels"]

    all_devices = []
    for lvl in levels:
        all_devices.extend(resolve_devices(lvl, prefix))

    total = len(all_devices)
    num_levels = len(levels)
    first_id = all_devices[0] if all_devices else "—"
    last_id = all_devices[-1] if all_devices else "—"

    return f"""# {ward} Monitoring System Guide — {hospital}

<!-- generated by scripts/generate_ward_docs.py -->

## What This System Monitors

WACH monitors **{total} AHUs across {num_levels} levels** at {hospital}.
Device IDs run from **{first_id}** to **{last_id}**, following the format
`{prefix}[LEVEL:02d][UNIT:02d]`.

Health scores are computed hourly from the ETL pipeline. Each AHU
receives a FAIR health index (0–100) and five component scores.

## Health Score Meaning

| Score | Tier | Action |
|-------|------|--------|
| 80–100 | Healthy | No action needed, scheduled PM only |
| 60–79 | Monitor | Watch closely, investigate trend |
| 40–59 | Maintenance | Schedule maintenance within 1–2 weeks |
| 0–39 | Critical | Immediate action required — escalate now |

## What the AI Can Answer

- Health status for any level or individual AHU
- Root cause analysis for poor health scores
- Maintenance recommendations (step-by-step for technicians)
- Financial impact of faults (TNB tariff penalties, energy waste)
- Trend analysis ("how has Level 5 been trending this week?")
- Explanations of FAIR scoring methodology

## What the AI Cannot Answer

- Real-time maintenance team availability or scheduling
- Spare parts stock or procurement
- Contractor quotes or work order status
- Clinical decisions or patient care matters

## When to Escalate Immediately

Critical-tier AHU in OT, ICU, PICU, or NICU → call on-call engineer
immediately. Do not wait for the next shift.

## Asking Good Questions

- "What is the health of Level 3?"
- "Which AHUs on Level 5 need attention?"
- "Why is e0501 showing a low power factor?"
- "What will it cost if e0302 stays in the Monitor tier for another month?"
- "How do I fix high THD on e0604?"
"""


# ── Main entry point ──────────────────────────────────────────────────────────

def main() -> None:
    config = load_config()

    if config is None:
        print("[ward_docs] WARNING: no ward_config.yml or ward_config.example.yml found. Skipping.")
        sys.exit(0)

    hospital = config.get("hospital", "?")
    ward = config.get("ward", "?")
    print(f"[ward_docs] Generating docs for: {ward}, {hospital}")

    RAG_DOCS_DIR.mkdir(parents=True, exist_ok=True)

    directory_md = generate_ward_directory(config)
    guide_md = generate_ward_system_guide(config)

    (RAG_DOCS_DIR / "ward_directory.md").write_text(directory_md, encoding="utf-8")
    print(f"[ward_docs] Written: backend/data/rag_docs/ward_directory.md")

    (RAG_DOCS_DIR / "ward_system_guide.md").write_text(guide_md, encoding="utf-8")
    print(f"[ward_docs] Written: backend/data/rag_docs/ward_system_guide.md")

    total = sum(
        len(resolve_devices(lvl, config.get("device_prefix", "e")))
        for lvl in config["levels"]
    )
    print(f"[ward_docs] Done. {total} devices across {len(config['levels'])} levels.")


if __name__ == "__main__":
    main()
